name: Default
on: [push, pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build
        run: npm run build
        env:
          CI: true
